name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"

      - name: Install Dependencies
        run: npm install

      - name: Build Website
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "/var/www/html"
            REMOTE_HOST: ${{ secrets.SERVER_IP }}
            REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
            TARGET: ${{ secrets.TARGET_DIRECTORY }}
            EXCLUDE: "/dist/, /node_modules/"
